services:
  chatbot:
    build: .
    container_name: buybuy_app
    env_file: .env
    ports:
      - "7860:7860"
    restart: always

  nginx:
    image: nginx:latest
    container_name: buybuy_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - chatbot